### ISSUE TITLE
Change bypass to enable

### ISSUE THREAD

**Issue by audiologic-vannoy** [fpga-open-speech-tools/simulink_models#16]
Currently, the bypass register is a 1 if we want to bypass the DSP, and a 0 if we want to do the DSP. Instead, it would make more sense if it was an enable register, where a 0 bypasses the DSP. This would match better with the enable toggle that our GUI shows. Having inverted logic is no fun.

This needs to be updated in all of the models:
- [x] bit crusher
- [x] echo
- [x] flanger
- [ ] simple_gain
- [ ] compression

**Comment by fe-wickham** [comment]
Looking at this simple_gain doesn't have a bypass register to change over, although an enable could certainly be added. Additionally compression I looked at the "sm_DynamicCompression" model which already had a "system_enable" register with the notable thing there it looks like only half the left channel was ever implemented. Not just the enable, but the rest of the DSP as the right chanel is currently just a gain being applied.

**Comment by tvannoy** [comment]
We probably don't need a bypass register for the simple gain, realistically. 

We might replace the compression model. If we don't replace the model, it'd be nice to be consistent and turn `system_enable` into `enable`
