### ISSUE TITLE
Refactor init scripts

### ISSUE THREAD

**Issue by audiologic-vannoy** [fpga-open-speech-tools/simulink_models#20]
# New features
Here are some of my ideas that will make the init scripts cleaner and more manageable. Feel free to add to this list.

- [ ] move common init scripts to a common folder
- [ ] create a script for various model-specific parameters (e.g. buffer sizes, etc.)

# Bug fixes and improvements
- [ ] be consistent when checking fastsim_flag (i.e. always check if it is true)

# Coding style
- [ ] change from snake_case to camelCase
- [ ] variable naming and readability improvements

**Comment by JustinWilliamsMSU** [comment]
I'm open to the idea of condensing functions including init_avalon_signals, init_control_signals, and init_test_signals into in-script functions within the sm_callback_init script. 

I think some code can be cut, comments rewritten to be descriptive and shorter, etc.

**Comment by audiologic-vannoy** [comment]
> I'm open to the idea of condensing functions including init_avalon_signals, init_control_signals, and init_test_signals into in-script functions within the sm_callback_init script.

That could work. I wonder if doing that would make those functions less discoverable, though.

**Comment by rksnider** [comment]
I think those should be individual init functions that would be called from
(found in) the \init folder.

Ross

**Comment by audiologic-vannoy** [comment]
> I think those should be individual init functions that would be called from (found in) the \init folder.

Are you proposing that there will be an init folder inside each model folder?  e.g. 
```
models
|--- simple_gain
     |--- init
          |--- init_script.m
     |--- sg.slx
```

**Comment by tvannoy** [comment]
We have another vote (via @fe-wickham) to turn some of the init functions into private functions inside the main init script. This reduces the number of files, which will make it easier for new developers/users to figure out what's going on without having to read through a bunch of documentation describing what each script does

**Comment by tvannoy** [comment]
We also threw around the idea of making the register settings a data file (e.g. json) instead of a script. For many cases, users will only need to modify the registers to match the model they are creating; most of the other scripts aren't touched.
