### ISSUE TITLE
Open MHA: O1 AR Filter Optimization Fixed Point Output size increasing

### ISSUE THREAD

**Issue by dack-fe** [fpga-open-speech-tools/simulink_models#56]
Because of the fixed point multiplication between the input and coefficients, the outputting signal is increasing. Do we want to convert this result to match the input size by removing the additional fractional bits?

[o1_ar_filter_optimization.slx](https://github.com/fpga-open-speech-tools/simulink_models/tree/openmha/models/open_mha/dynamic_range_compression/gain_calculation/attack_decay/attack_decay_filter/o1_ar_filter_optimization)

**Comment by matthewblunt** [comment]
Yes, I think removing the fractional bits is the correct move. Because the signal is fed into the gain table afterword, the lost precision will not matter as the gain acquired from the table will be almost exactly the same.

**Comment by dack-fe** [comment]
Currently being handled with parameters set in init scripts
