### ISSUE TITLE
Open MHA: Attack and Decay Optimization

### ISSUE THREAD

**Issue by dack-fe** [fpga-open-speech-tools/simulink_models#57]
Verify the attack and decay optimization compared to the original source code from Open MHA - dc.cpp - Line 282
- [attack_decay_filter.slx](https://github.com/fpga-open-speech-tools/simulink_models/tree/openmha/models/open_mha/dynamic_range_compression/gain_calculation/attack_decay/attack_decay_filter/attack_decay_filter.slx)

- I have added some comments explaining the optimization, however I am confused on the final logic step of the block

**Comment by dack-fe** [comment]
@matthewblunt and @fe-wickham Can you please review the update to the [Attack & Decay Filter Block.](51ef424)

**Comment by matthewblunt** [comment]
After looking it over, I think this implementation makes sense. It's still a bit confusing when I compare it to the documentation but I think it could very well be correct.

**Comment by dack-fe** [comment]
I just update the comment in the [Simulink Model](65fefdc).  I will review the documentation that Matt provided as well as implement MATLAB Validation without the optimization on Monday.

The MATLAB Validation will use 2 complete attack and release filters and the corresponding coefficients based on the source code.

**Comment by dack-fe** [comment]
@matthewblunt and @fe-wickham Can you please review the Attack & Decay Filter Block along with the model parameters and validation scripts?

**Comment by dack-fe** [comment]
Updated with non-optimized attack and decay filter
