### ISSUE TITLE
udpate HDL workflow advisor

### ISSUE THREAD

**Issue by audiologic-vannoy** [fpga-open-speech-tools/simulink_models#8]
## Changes
- add target frequency
- add prefix to generate entities/files to avoid collisions

## Models
- [x] flanger
- [x] echo
- [x] bitcrusher
- [x] simple gain
- [x] fir filter

## Thoughts
Since this file doesn't change between models, perhaps it should be isolated into another directory and referenced by each model. This would make it so we don't have to change the file in multiple places...

## Investigation
The HDL coder is generating multiple files for the same entities. For example, blockA exists in two different places in the model, and the HDL coder generates two files for blockA with different names, but the actual logic is *exactly* the same. There should be a way to reuse identical entities.

**Comment by tvannoy** [comment]
The hdlworkflow file has moved into [simulink_codegen](https://github.com/fpga-open-speech-tools/simulink_codegen), so now all models reference the same file (yay no duplication!)

Closed by https://github.com/fpga-open-speech-tools/simulink_codegen/commit/8056e9df77766a97b08bb7b48e63e3a5ae3c3238

---

The part of this issue about generating multiple entities still exists, but has been moved into https://github.com/fpga-open-speech-tools/simulink_codegen/issues/4
